http://www.cs.cornell.edu/cv/SummerSchool/Introduction.pdf

An order-$d$ tensor $\mathcal{A} \in \mathbb{R}^{n_1 \times ... \times n_d}$ is a real $d$-dimensional array $\mathcal{A}(1:n_1,...,1:n_d)$ where the index range in the $k$-th mode is from 1 to $n_k$.

In [5]:
import numpy as np
import numpy.linalg as la

Generate random matrix

In [3]:
x = np.random.rand(16).reshape(4,4)

In [4]:
x

array([[0.54227851, 0.66889601, 0.45727073, 0.62933098],
       [0.47801063, 0.73891157, 0.59305438, 0.03116649],
       [0.44853368, 0.9819833 , 0.00696085, 0.16644272],
       [0.95718035, 0.83565228, 0.26768417, 0.35318074]])

SVD Decomposition
$$
\begin{bmatrix}
a_{11} a_{12} \\ a_{21} a_{22}
\end{bmatrix}
=
\begin{bmatrix}
u_{11} u_{12} \\ u_{21} u_{22}
\end{bmatrix}
\begin{bmatrix}
\sigma_1 0 \\ 0 \sigma_2
\end{bmatrix}
\begin{bmatrix}
v_{11} v_{12} \\ v_{21} v_{22}
\end{bmatrix}^T
$$

In [6]:
u, s, vh = la.svd(x)

In [9]:
print("U: {}\n".format(u))
print("S: {}\n".format(s))
print("V: {}\n".format(vh))

U: [[-0.49352684  0.62107755  0.32417229 -0.51537002]
 [-0.4438384   0.13884032 -0.88455544  0.03595165]
 [-0.4546231  -0.77077561  0.08935848 -0.43730751]
 [-0.59393314 -0.02984968  0.32324768  0.73611369]]

S: [2.21956252 0.51063197 0.44009029 0.31153589]

V: [[-0.56416675 -0.72123642 -0.2933221  -0.27476544]
 [ 0.05654524 -0.51662592  0.69127066  0.50204101]
 [ 0.23279629 -0.17928025 -0.6571485   0.69413279]
 [ 0.79014201 -0.42517559 -0.06529069 -0.43662163]]



Reconstruct original matrix using SVD components

In [17]:
reconstructed = u.dot(np.diag(s)).dot(vh)

In [18]:
np.allclose(x, reconstructed)

True

Reconstruct original matrix with vectors

In [13]:
x_ = np.zeros((4,4))

In [15]:
for i in range(4):
    x_ += s[i] * np.outer(u[:,i], vh[i,:])

In [19]:
np.allclose(x, x_)

True

Kronecker Product

$$
\begin{bmatrix}
a \\ b
\end{bmatrix}
\otimes
\begin{bmatrix}
c \\ d
\end{bmatrix}
=
\begin{bmatrix}
ac \\ ad \\ bc \\ bd
\end{bmatrix}
$$

In [20]:
x_kronecker = np.zeros((16,))

In [21]:
for i in range(4):
    x_kronecker += s[i] * np.kron(u[:,i], vh[i,:])

In [24]:
x_kronecker

array([0.54227851, 0.66889601, 0.45727073, 0.62933098, 0.47801063,
       0.73891157, 0.59305438, 0.03116649, 0.44853368, 0.9819833 ,
       0.00696085, 0.16644272, 0.95718035, 0.83565228, 0.26768417,
       0.35318074])

In [25]:
np.allclose(x.reshape(16,), x_kronecker)

True

If $\mathcal{R}$ has unit rank, then $\mathcal{R} = (r_{ijk}), r_{ijk} = h_kg_jf_i$

If $\mathcal{R} \in \mathbb{R}^{2\times2\times2\times}$ has unit rank then there exist $f,g,h \in \mathbb{R}^2$ such that

$$
\begin{bmatrix}
r_{111} \\ r_{211} \\ r_{121} \\ r_{221} \\ r_{112} \\ r_{212} \\ r_{122} \\ r_{222}  
\end{bmatrix}
=
\begin{bmatrix}
h_1 \\ h_2
\end{bmatrix}
\otimes
\begin{bmatrix}
g_1 \\ g_2
\end{bmatrix}
\otimes
\begin{bmatrix}
f_1 \\ f_2
\end{bmatrix}
$$